### ISSUE TITLE
能否直接启动时就自动修改代理

### ISSUE THREAD

**Issue by sephrioth** [goodbest/Alfred_SurgeConf_Switcher#1]
有时切换配置后, 发现无法联网, 才注意到忘记修改网络设置成Surge对应的http和https代理, 很是麻烦. 能否直接把修改代理放在workflow中呢?

**Comment by goodbest** [comment]
一般情况下，代理设置都是不变的，切换surge配置文件的时候并不需要改变代理的状态。
因此推荐配合readme里提到的`proxy switcher`使用。

**Comment by sephrioth** [comment]
我明白你的意思, 因为我现在是Surge和ss混用, 所以经常会发生混乱.   ss开启后就会自动设置对应的proxy模式, 我觉得这样更方便...  如果关闭surge也可以自动关掉代理也会更好.  我自己先在你的workflow折腾看看~ 多谢你的工作~

**Comment by sephrioth** [comment]
最主要是离不开SS的Final Speed 黑科技啊. - -
